# Generated by Django 3.1.5 on 2021-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('winner_points', models.PositiveIntegerField()),
                ('excluded_feature', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected', models.CharField(max_length=255)),
                ('trained_against', models.CharField(max_length=255)),
            ],
        ),
    ]
